import {
  siRust,
  siPython,
  siJavascript,
  siReact,
  siDocker,
  siMongodb,
  siRedis,
  siGit,
  siPytorch,
  siGraphql,
  siFlask,
  siFastapi,
  siWebassembly,
  siOpencv,
  siSqlite,
  siNodedotjs,
} from 'simple-icons'

export const STACK_ICONS = {
  'Rust':                 siRust,
  'Python':               siPython,
  'JavaScript':           siJavascript,
  'React':                siReact,
  'Docker':               siDocker,
  'MongoDB':              siMongodb,
  'Redis':                siRedis,
  'Git':                  siGit,
  'PyTorch':              siPytorch,
  'GraphQL':              siGraphql,
  'Flask':                siFlask,
  'FastAPI':              siFastapi,
  'WebAssembly':          siWebassembly,
  'OpenCV':               siOpencv,
  'SQLite':               siSqlite,
  'Node.js':              siNodedotjs,
}
